[tools]
go = "1.25.5"
node = "lts"
shfmt = "3.6.0"
shellcheck = "0.9.0"
bats = "1.8.2"
python = "3.14.2"
dotnet = ["8", "9", "10"]
flutter = { version = "3.38.9", platforms = """
[linux-arm64]
url = 'https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_arm64_{{ version | replace(from="-stable", to="") }}-stable.tar.xz'

[linux-x64]
url = 'https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ version | replace(from="-stable", to="") }}-stable.tar.xz'
""", url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ version }}-stable.zip", version_json_path = ".releases[?channel=stable].version", version_list_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json" }
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:claudekit-cli" = "latest"
"npm:corepack" = "latest"
"npm:npm" = "latest"
"npm:opencode-ai" = "latest"
"npm:repomix" = "latest"
"npm:rmbg-cli" = "latest"
"npm:wrangler" = "latest"
